### ISSUE TITLE
Chat makes his polished version of effect size FAQ / exemplar

### ISSUE THREAD

**Issue by mjskay** [transparentstats/guidelines#11]

**Comment by chatchavan** [comment]
Done, in [a separate branch](https://github.com/chatchavan/guidelines/tree/alt-format) in my repository. The compiled version can be previewed [here](http://htmlpreview.github.io/?https://github.com/chatchavan/guidelines/blob/alt-format/effectsize_example.nb.html).

**Comment by chatchavan** [comment]
Also documented [design rationale](https://raw.githubusercontent.com/chatchavan/guidelines/alt-format/design_rationale.md)

**Comment by mjskay** [comment]
Cool! Can you compile it using a template that includes output? I don't see code output on the compiled version.

**Comment by chatchavan** [comment]
Done.

**Comment by chatchavan** [comment]
Also included Pierre's text modification.

**Comment by mjskay** [comment]
Sweet, thanks!

**Comment by mjskay** [comment]
Re-closing this.
