### ISSUE TITLE
Move exemplars into bookdown with automated workflow 

### ISSUE THREAD

**Issue by mjskay** [transparentstats/guidelines#16]
Before our first release, I think we'll want to move the guidelines into [bookdown](https://bookdown.org/) format and set up an easy publishing-to-web process (of which bookdown seems to have a few options).

**Comment by mjskay** [comment]
See the bookdown docs: https://bookdown.org/yihui/bookdown/

We probably want to use the K-M rendering approach so that code from different guidelines do not create conflicts. See here:  https://bookdown.org/yihui/bookdown/new-session.html

Then we could set up automated rendering through github and Travis per here: https://bookdown.org/yihui/bookdown/github.html

Anyone want to take this on? @chatchavan @dragice @steveharoz @shionguha?

**Comment by chatchavan** [comment]
I'll need this for one of my projects, so I'll have a stab at this.

**Comment by mjskay** [comment]
Awesome, thanks!

**Comment by chatchavan** [comment]
- [ ] Automatic build from Travis (I'm currently looking into this.)
- [ ] Add to wiki:
    - [ ] Modification required to `_book.yml` when a new file is added.
    - [ ] Use "Build book" on the "Build pane" to compile instead of the "Knit" button
    - [ ] Use `knitr::includegraphics()` for images
    - [ ] update wiki to state that {#id} format is the way to make heading ids in bookdown

**Comment by mjskay** [comment]
@chatchavan Is this issue closeable given your recent work?

**Comment by chatchavan** [comment]
Yup. I added stuff in the checklist above to the [Style Guide](https://github.com/transparentstats/guidelines/wiki/Style-Guide)
