### ISSUE TITLE
Merge style guides for exemplars and FAQ

### ISSUE THREAD

**Issue by mjskay** [transparentstats/guidelines#26]

**Comment by steveharoz** [comment]
Some notes I took from the meeting

**Format and content of exemplar**
- Main Scenario / when to use
- Code
- How to report
- [optional] Alternative scenarios

**Comment by mjskay** [comment]
Notes I took:

*style guide for FAQ*
- should be as brief as possible
- avoid repitation
- use citations for almost every claim
- address authors and reviewers
- focus on what rather than how
- stay at high level
- should say when some approaches are better than others
- briefly define terms
- try to order questions logically
- FAQ should be compatible with random access, therefore have internal links to other questions
- quotes as backup
- citations should try to be more specific, cite page numbers for papers and chapters for books

*style guide for exemplars*
- should have concrete context of a study with research question
- want exemplars to be exemplars
- sometimes there is a partial ordering on what is an exemplar; e.g. approach C and D are equally okay. Can include both in an exemplar with explanation.
- may need anti-exemplars in some guidelines
- quotes for text to include in the paper are good.

**Comment by mjskay** [comment]
This is now done [here](https://github.com/transparentstats/guidelines/wiki/Style-Guide). @steveharoz @shionguha @dragice @chatchavan
