### ISSUE TITLE
Decide on significant figures format

### ISSUE THREAD

**Issue by steveharoz** [transparentstats/guidelines#33]
What should the format be?

General agreement:
- `format_num(12345)` -> `"12345"`  
- `format_num(1.2345)` -> `"1.23"`
- `format_num(0.0012345)` -> `"0.00123"`

Questions:
- `format_num(1)` -> `"1.00"` or `1` ?

**Comment by mjskay** [comment]
> `format_num(1) -> "1.00" or 1 ?`

I am fine with either.

**Comment by mjskay** [comment]
Okay, given that discussion on this died, if I get two upvotes on this comment I will resolve this issue and update the wiki to go with what we ended up using in the effect size exemplar:

```r
format_num <- function(nums, sigdigits = 3) gsub("\\.$", "", formatC(nums, sigdigits, format = "fg", flag="#"))
```

Which gives this style:

```r
format_num(12345) -> "12345"
format_num(1.2345) -> "1.23"
format_num(0.0012345) -> "0.00123"
format_num(1) -> "1.00" 
```

**Comment by chatchavan** [comment]
+1

**Comment by mjskay** [comment]
@steveharoz ?

**Comment by dragice** [comment]
+1

I don't think we'll find a universal format_num that works for all exemplars so let's not worry too much about this.

**Comment by mjskay** [comment]
Sounds good, wiki updated.
