### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by steveharoz** [transparentstats/guidelines#37]
Since the goal is to eventually include a broader set of contributors, we should probably consider a code of conduct.

[This one is commonly used](http://contributor-covenant.org/version/1/4/)

**Comment by mjskay** [comment]
I think this is an excellent idea. I also like the code of conduct you suggested.  I'd say put it on the wiki and link it from the wiki main page?

To implement it, we need some kind of contact email address. I will create one.

**Comment by mjskay** [comment]
The address I created is: core@transparentstatistics.org

**Comment by steveharoz** [comment]
I added it to the [wiki](https://github.com/transparentstats/guidelines/wiki). If it looks fine, just close this issue.

**Comment by mjskay** [comment]
Thanks! Looks good to me.
