### ISSUE TITLE
Create an automated workflow to compile .Rmd to make it easily readable by the public

### ISSUE THREAD

**Issue by chatchavan** [transparentstats/guidelines#40]
@steveharoz @mjskay: Do you have any experience on setting up an auto-build system that will take our .Rmd from github, compile it, and make the result publicly available in a certain URL?

**Comment by mjskay** [comment]
I haven't done this, but I have heard of people using github pages to do it, possibly with Travis for autocompilation. 

I think we would change over to bookdown and then adopt one of the strategies on this page:

https://bookdown.org/yihui/bookdown/github.html

**Comment by mjskay** [comment]
See also #16

**Comment by chatchavan** [comment]
OK. This seems to be a duplicate then.
