### ISSUE TITLE
Make pluralistic analysis of simple effect size exemplar

### ISSUE THREAD

**Issue by mjskay** [transparentstats/guidelines#42]
Per #38:

1. Make the first plot of the two groups purely descriptive (no inferential intervals)

2. Use the t interval as the main version of the simple effect size analysis

3. Add a separate supplemental document that compares the various approaches to the simple effect size analysis. That document will be linked to from the simple effect size analysis, with a statement like this:

> There are several possible approaches to estimating the uncertainty in the difference between the two groups. For simplicity, we show one possible approach in this exemplar, but we provide a non-exhaustive comparison of a few other approaches here (insert link).

My only remaining question is to @chatchavan 's last comment on #38:

> Let's leave only data in there and defer violin plot to an FAQ about data visualization. Reason: simplicity for readers without adequate background.

I see this as:

- pro: simplicity
- con: possibly no longer an exemplar of descriptive visualization of data

Possible compromise: a Wilkinson dotplot instead?

Plus now we need a guideline for descriptive stats. I'll make an issue :)

**Comment by chatchavan** [comment]
Wilkinson dotplot is a good idea.
