### ISSUE TITLE
Figure out how we want to format tables in bookdown

### ISSUE THREAD

**Issue by mjskay** [transparentstats/guidelines#51]
The bookdown default table formatting doesn't give nice HTML table output like r notebooks do. Instead we get text tables. E.g.:

```r
log_interval
```

```
## # A tibble: 1 x 5
##   estimate conf.low conf.high .prob               method
##      <dbl>    <dbl>     <dbl> <dbl>                <chr>
## 1 107.2028 85.23455  131.7186  0.95 lognormal regression
```

The suggested fix according to the [bookdown docs](https://bookdown.org/yihui/bookdown/tables.html) is to use the `kable` function from `knitr`:

```r
kable(log_interval)
```

Which outputs a table that is formatted nicely by bookdown. On the other hand, it litters the reader-visible docs with formatting code that is not essential to understanding the content. 

Another option is to run code chunks that output tables but hide their output, and follow them with code chunks that output nice tables using `kable` but whose code is hidden. Like this:

<pre lang="no-highlight"><code>```{r, results = "hide"}
log_interval
```

```{r, echo = FALSE}
kable(log_interval)
```
</code></pre>

So that readers just see the first line (`log_interval`) plus the HTML table output, and don't see the second line (`kable(log_interval)`) that actually output the table.

In sum, possible table approaches might be:

1. *status quo*. Leave the output as text tables. Possibly tweak `options(width = )` to show more columns in output.

2. *use and show kable*. Use `kable(x)` and have readers see `kable(x)`.

3. *use and hide kable*. Use `kable(x)` and have readers see `x`.

**Comment by steveharoz** [comment]
I just realized the formatting of the within-subject section was heavily modified (shakes fist angrily), I originally put `x %>% kable()` which just adds a small bit at the end.

**Comment by mjskay** [comment]
Nevermind, I figured out how to fix this. There is an option to get bookdown to do the automatic table generation. It's a minor fix so I'll commit directly to the branch.
