### ISSUE TITLE
Develop code style guidelines for exemplars

### ISSUE THREAD

**Issue by mjskay** [transparentstats/guidelines#6]
Probably to be done after / as we polish the effect size exemplar.

**Comment by chatchavan** [comment]
We should probably use a linter to automate this.

**Comment by mjskay** [comment]
We can likely adopt (or fork and slightly modify) the tidyverse style guide for simplicity: http://style.tidyverse.org/

It works with lintr, which I believe has RStudio integration. There are a few minor quibbles I have with that style guide but nothing major, and lintr is configurable I believe.

**Comment by chatchavan** [comment]
[Wiki page for exemplar](https://github.com/transparentstats/guidelines/wiki/Exemplar-Style-Guide)

**Comment by chatchavan** [comment]
Just read through the tidyverse style guide again. I think we can adopt it entirely and make our additions as specified in the wiki page above.

**Comment by mjskay** [comment]
I'm happy with that. I think it also means we won't be teaching people "bad" habits as far as common R style is concerned --- at the very least, our examples will "look like" examples of best practices they will find elsewhere, like vignettes in the tidyverse.

**Comment by mjskay** [comment]
This is done now, more or less. Adding an issue (post-draft release) for getting a linter set up.
