### ISSUE TITLE
Make a friction-less workflow for early contributions to the guideline.

### ISSUE THREAD

**Issue by chatchavan** [transparentstats/guidelines#7]
E.g., start early draft as Google Docs to allow as many people as possible to contribute. Once it's stable (whether agreement or disagreement), port the text to git.

**Comment by mjskay** [comment]
I think this is reasonable for the FAQs, at least in the short term. Does this make sense for exemplars though? I suspect starting in RMarkdown on git will make the most sense for the exemplars.

**Comment by chatchavan** [comment]
Good point. If the flow of writing the guideline is the same as we had on Saturday, the exemplars seem to be decoupled from the FAQ.

How about we start FAQ in Google Doc. If there's no change for two weeks, we port it to Rmd and put on git (and freeze the doc to keep history and comments for reference)

For exemplars, we start them in Rmd on got directly.

Cheers,
Chat

**Comment by mjskay** [comment]
Sounds good

**Comment by mjskay** [comment]
This workflow is mostly up to date in the contributing wiki now, so I am closing this.
